"use client";

import { Dices, ImageIcon } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";

import { Button } from "@/_components/ui/button";
import { cn } from "@/_lib/utils";

const DICEBEAR_VERSION = "9.x";

/** Curated DiceBear styles (path segment only — never interpolate user input here). */
export const AVATAR_STYLES = [
  "lorelei",
  "adventurer",
  "avataaars",
  "notionists",
  "open-peeps",
  "bottts",
  "pixel-art",
  "fun-emoji",
  "identicon",
  "shapes",
] as const;

export type AvatarStyle = (typeof AVATAR_STYLES)[number];

function diceBearUrl(style: AvatarStyle, seed: string, size: number): string {
  const safeSeed = seed.trim().slice(0, 80) || "member";
  const params = new URLSearchParams({
    seed: safeSeed,
    size: String(size),
    backgroundColor: "transparent",
  });
  return `https://api.dicebear.com/${DICEBEAR_VERSION}/${style}/svg?${params.toString()}`;
}

function randomSeed(): string {
  try {
    return crypto.randomUUID().replace(/-/g, "").slice(0, 16);
  } catch {
    return String(Math.random()).slice(2, 18);
  }
}

function parseDicebearAvatar(url: string): { style: AvatarStyle; seed: string } | null {
  try {
    const u = new URL(url.trim());
    if (u.hostname !== "api.dicebear.com") return null;
    const segs = u.pathname.split("/").filter(Boolean);
    if (segs.length < 3) return null;
    const style = segs[1] as AvatarStyle;
    if (!AVATAR_STYLES.includes(style)) return null;
    const seed = u.searchParams.get("seed");
    if (!seed) return null;
    return { style, seed: seed.slice(0, 80) };
  } catch {
    return null;
  }
}

export type AvatarPickerProps = {
  /** Current `avatar_url` from the form. */
  value: string;
  onChange: (url: string) => void;
  /** Used to build a sensible default seed before the user shuffles. */
  defaultSeedSource?: string;
  className?: string;
};

export function AvatarPicker({ value, onChange, defaultSeedSource = "member", className }: AvatarPickerProps) {
  const initialFromUrl = useMemo(() => parseDicebearAvatar(value), [value]);
  const [style, setStyle] = useState<AvatarStyle>(initialFromUrl?.style ?? "lorelei");
  const [seed, setSeed] = useState(initialFromUrl?.seed ?? (defaultSeedSource.trim().slice(0, 80) || "member"));

  useEffect(() => {
    const parsed = parseDicebearAvatar(value);
    if (parsed) {
      setStyle(parsed.style);
      setSeed(parsed.seed);
    }
  }, [value]);

  const previewUrl = useMemo(() => diceBearUrl(style, seed, 128), [style, seed]);

  const trimmedValue = value.trim();
  const customImageUrl = /^https?:\/\//i.test(trimmedValue) && !parseDicebearAvatar(trimmedValue) ? trimmedValue : null;
  const previewSrc = customImageUrl ?? previewUrl;

  const apply = useCallback(
    (nextStyle: AvatarStyle, nextSeed: string) => {
      setStyle(nextStyle);
      setSeed(nextSeed);
      onChange(diceBearUrl(nextStyle, nextSeed, 256));
    },
    [onChange],
  );

  const shuffle = useCallback(() => {
    const s = randomSeed();
    setSeed(s);
    onChange(diceBearUrl(style, s, 256));
  }, [onChange, style]);

  return (
    <div className={cn("space-y-4", className)}>
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start">
        <div className="flex shrink-0 flex-col items-center gap-2">
          <div className="relative h-28 w-28 overflow-hidden rounded-2xl border border-white/15 bg-black/30 ring-1 ring-white/5">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={previewSrc} alt="" className="h-full w-full object-cover" width={112} height={112} />
          </div>
          <p className="max-w-[9rem] text-center text-[10px] text-phronis-muted">Preview</p>
        </div>
        <div className="min-w-0 flex-1 space-y-3">
          <div className="flex flex-wrap gap-2">
            <Button type="button" variant="outline" size="sm" className="border-white/15" onClick={shuffle}>
              <Dices className="mr-2 h-4 w-4" aria-hidden />
              New look
            </Button>
            <Button
              type="button"
              variant="outline"
              size="sm"
              className="border-white/15"
              onClick={() => apply(style, defaultSeedSource.trim().slice(0, 80) || "member")}
            >
              Reset to name
            </Button>
          </div>
          {customImageUrl ? (
            <p className="text-[11px] text-phronis-muted">
              Showing your saved image. Pick a style below to replace it with a generated avatar.
            </p>
          ) : null}
          <p className="text-xs leading-relaxed text-phronis-muted">
            Pick a style below. Avatars are generated by{" "}
            <a href="https://www.dicebear.com" className="text-phronis-teal underline-offset-2 hover:underline" target="_blank" rel="noopener noreferrer">
              DiceBear
            </a>{" "}
            (external).
          </p>
        </div>
      </div>

      <div>
        <p className="mb-2 flex items-center gap-2 text-xs font-medium uppercase tracking-wider text-phronis-muted">
          <ImageIcon className="h-3.5 w-3.5" aria-hidden />
          Choose style
        </p>
        <div className="grid grid-cols-5 gap-2 sm:grid-cols-5 md:grid-cols-10">
          {AVATAR_STYLES.map((st) => {
            const thumb = diceBearUrl(st, seed, 64);
            const selected = !customImageUrl && st === style;
            return (
              <button
                key={st}
                type="button"
                title={st}
                aria-label={`Avatar style ${st}`}
                aria-pressed={selected}
                onClick={() => apply(st, seed)}
                className={cn(
                  "relative aspect-square overflow-hidden rounded-xl border transition-colors",
                  selected ? "border-phronis-teal ring-2 ring-phronis-teal/40" : "border-white/10 hover:border-white/25",
                )}
              >
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={thumb} alt="" className="h-full w-full object-cover" width={64} height={64} loading="lazy" />
              </button>
            );
          })}
        </div>
      </div>
    </div>
  );
}
