import type { Semester } from "./types";

/** Semester 4 — DeFi mechanics and systemic risk (~12 h). */
export const SEMESTER_04: Semester = {
  id: "s4",
  number: 4,
  title: "DeFi: Primitives, Composability, and Systemic Risk",
  description:
    "Automated market makers, lending protocols, oracles, liquidations, stablecoin loops, and how composability amplifies both innovation and failure modes.",
  prerequisites: ["Semester 3 complete", "Comfort reading Etherscan-style explorers"],
  modules: [
    {
      id: "s4-m1",
      title: "AMMs, Liquidity, and Impermanent Loss",
      description: "Constant product intuition, concentrated liquidity, and LP economics.",
      lessons: [
        {
          id: "s4-m1-l1",
          title: "x*y=k and Beyond: Curve Family Intuition",
          synopsis: "Why bonding curves exist; price impact; fee tiers as segmentation.",
          estimatedMinutes: 85,
          objectives: [
            "Derive price impact story without full calculus.",
            "Explain impermanent loss in words a trader respects.",
            "Contrast v2 vs concentrated liquidity UX risks.",
          ],
          readings: [{ title: "Uniswap v2 whitepaper + v3 overview (skim math)", studyGuide: "Focus on graphs.", estimatedMinutes: 50 }],
          lectureOutline: ["Arbitrage as correctness mechanism", "MEV sandwich preview", "TWAP oracle from pools"],
          lab: {
            title: "IL Spreadsheet",
            scenario: "Model two assets with correlated drift; show IL vs HODL for 3 scenarios.",
            deliverable: "Sheet + 1-page interpretation for a treasury committee.",
            rubricHints: ["States assumptions", "No 'IL is always bad' slogan"],
          },
          selfCheckQuestions: ["Who earns fees when volume is toxic?", "When is LPing rational?"],
        },
        {
          id: "s4-m1-l2",
          title: "Liquidity Bootstrapping and LBP Risks",
          synopsis: "Fair launch myths; bot dynamics; transparency requirements.",
          estimatedMinutes: 78,
          objectives: ["Describe auction-like launches on-chain.", "Explain bot advantage in thin pools.", "List disclosure checklist for communities."],
          readings: [{ title: "Fjord Foundry / Copper-style docs (mechanics)", studyGuide: "Note parameters.", estimatedMinutes: 35 }],
          lectureOutline: ["Block zero sniping", "Allowlist tradeoffs", "KYC perimeters"],
          lab: {
            title: "Launch Parameter Review",
            scenario: "Given a hypothetical LBP config, stress-test with adversarial bot.",
            deliverable: "Bullet analysis + parameter tweaks + residual risk.",
            rubricHints: ["Concrete numbers optional", "Names MEV"],
          },
          selfCheckQuestions: ["What does 'fair' mean on a public chain?", "How does allowlist leak?"],
        },
        {
          id: "s4-m1-l3",
          title: "DEX Aggregators and Routing",
          synopsis: "Split routes, price impact limits, and partial fills as user education topic.",
          estimatedMinutes: 75,
          objectives: ["Explain why quotes move.", "Describe slippage tolerance footgun.", "Relate to approval surfaces."],
          readings: [{ title: "1inch / Paraswap docs — routing overview", studyGuide: "User-level only.", estimatedMinutes: 25 }],
          lectureOutline: ["RFQ vs AMM path", "Private mempools tradeoffs", "Wallet simulation limits"],
          lab: {
            title: "User Education Copy",
            scenario: "Write 6 short in-app strings explaining slippage, price impact, and failed txs.",
            deliverable: "Copy deck + FAQ for support.",
            rubricHints: ["Plain language", "Warns on infinite approvals"],
          },
          selfCheckQuestions: ["Why can a swap succeed but user unhappy?", "What is partial fill?"],
        },
      ],
    },
    {
      id: "s4-m2",
      title: "Lending, Liquidations, and Oracles",
      description: "Collateral factors, health factors, cascade liquidations.",
      lessons: [
        {
          id: "s4-m2-l1",
          title: "Collateralized Debt: Aave / Compound Mental Model",
          synopsis: "cToken/aToken abstraction; interest rate models at brochure depth.",
          estimatedMinutes: 88,
          objectives: ["Walk deposit → borrow → repay lifecycle.", "Explain utilization-driven rates.", "Identify governance knobs."],
          readings: [{ title: "Aave docs — risk parameters appendix", studyGuide: "Pick three assets, compare params.", estimatedMinutes: 45 }],
          lectureOutline: ["e-mode correlated risk", "Isolation mode", "Caps and freezes"],
          lab: {
            title: "Parameter Comparison Memo",
            scenario: "Compare two lending markets for the same asset wrapper; explain risk difference.",
            deliverable: "2-page memo + table of caps/LTV/oracles.",
            rubricHints: ["Names oracle feeds", "Notes bridge asset risk"],
          },
          selfCheckQuestions: ["What happens if oracle lags spot?", "Who absorbs bad debt?"],
        },
        {
          id: "s4-m2-l2",
          title: "Liquidations: Incentives, Bots, and Social Externalities",
          synopsis: "Liquidator profit as safety valve; cascade risks during volatility.",
          estimatedMinutes: 82,
          objectives: ["Math-lite health factor story.", "Explain liquidation bonus.", "Describe bad debt socialization."],
          readings: [{ title: "Gauntlet / Chaos Labs public reports (skim one)", studyGuide: "Focus on liquidation graphs.", estimatedMinutes: 40 }],
          lectureOutline: ["Sequencer ordering effects", "Auction vs fixed spread", "Insurance funds"],
          lab: {
            title: "Liquidation Timeline",
            scenario: "Reconstruct a historical volatile day from public dashboards (any chain).",
            deliverable: "Timeline graphic + 10 bullets on who acted when.",
            rubricHints: ["Cites sources", "Notes oracle updates"],
          },
          selfCheckQuestions: ["Why are liquidations public goods?", "What is toxic liquidation flow?"],
        },
        {
          id: "s4-m2-l3",
          title: "Oracles: Aggregation, Manipulation, and Delay Games",
          synopsis: "Chainlink-style feeds vs DEX TWAP; oracle delay vs freshness tradeoff.",
          estimatedMinutes: 85,
          objectives: ["Explain medianized multi-source feeds at high level.", "Give two historical manipulation sketches.", "Propose monitoring metrics."],
          readings: [{ title: "Chainlink data feeds docs + one academic oracle paper intro", studyGuide: "Focus on liveness assumptions.", estimatedMinutes: 45 }],
          lectureOutline: ["Heartbeat vs deviation thresholds", "Sequencer downtime coupling", "L2 native oracles"],
          lab: {
            title: "Oracle Risk Register",
            scenario: "Your protocol uses one primary feed + backup. Build risk register with mitigations.",
            deliverable: "Register + test plan for stale price.",
            rubricHints: ["Includes sequencer failure", "Defines escalation"],
          },
          selfCheckQuestions: ["When is TWAP safer than spot?", "What is upward manipulation?"],
        },
      ],
    },
    {
      id: "s4-m3",
      title: "Composability, Cascades, and Macro Crypto",
      description: "Money legos until the tower wobbles; contagion case studies.",
      lessons: [
        {
          id: "s4-m3-l1",
          title: "Rehypothecation and Recursive Leverage Loops",
          synopsis: "How the same collateral backs multiple claims via interlocking protocols.",
          estimatedMinutes: 80,
          objectives: ["Draw a loop diagram for stETH-style narratives (generic).", "Explain why NAV ≠ redeemable during stress.", "Discuss deleverage spirals."],
          readings: [{ title: "Postmortems of major depeg events (read 2)", studyGuide: "Extract common graph pattern.", estimatedMinutes: 55 }],
          lectureOutline: ["Liquidity vs solvency distinction", "Run dynamics on-chain", "Governance intervention ethics"],
          lab: {
            title: "Contagion Map",
            scenario: "Pick an ecosystem; map top 10 protocols by TVL links (directional arrows).",
            deliverable: "Graph + 3 cascade stories plausible from structure alone.",
            rubricHints: ["Uses public data", "Marks confidence levels"],
          },
          selfCheckQuestions: ["What metric overstates safety?", "When does governance freeze help?"],
        },
        {
          id: "s4-m3-l2",
          title: "Insurance, Bug Bounties, and Protocol-Owned Reserves",
          synopsis: "Why 'insured' DeFi is rarely full coverage; incentive alignment of bounty programs.",
          estimatedMinutes: 76,
          objectives: ["Compare Nexus Mutual style coverage limits.", "Explain bounty tiering.", "Assess POV reserves as volatility buffer."],
          readings: [{ title: "Immunefi documentation + one insurance protocol FAQ", studyGuide: "Note exclusions.", estimatedMinutes: 35 }],
          lectureOutline: ["Moral hazard in coverage", "War room funding", "RetroPGF as ex-post insurance"],
          lab: {
            title: "Incident Budget",
            scenario: "Allocate hypothetical $5M across audits, bounties, insurance, reserves.",
            deliverable: "Budget sheet + 1-page defense in front of community.",
            rubricHints: ["Justifies tradeoffs", "Notes unknown unknowns"],
          },
          selfCheckQuestions: ["Why exclude oracle failures?", "What is safe harbor?"],
        },
        {
          id: "s4-m3-l3",
          title: "Regulatory Geography as System Parameter",
          synopsis: "How jurisdictional friction shapes product design (high level, not legal advice).",
          estimatedMinutes: 78,
          objectives: ["List major regulatory themes cited publicly for DeFi.", "Explain travel rule touchpoints at UX level.", "Discuss decentralization theater risks."],
          readings: [{ title: "FATF guidance summaries from reputable law firms (non-advice)", studyGuide: "Glossary only.", estimatedMinutes: 40 }],
          lectureOutline: ["Sanctions screening", "Stablecoin issuer models", "Developer liability debates"],
          lab: {
            title: "Product Principles",
            scenario: "Draft neutral 'build principles' for an open-source team navigating compliance uncertainty.",
            deliverable: "Principles doc + escalation to counsel triggers.",
            rubricHints: ["Not legal advice disclaimer", "Concrete triggers"],
          },
          selfCheckQuestions: ["What is VASP?", "Why can't code alone answer law?"],
        },
      ],
    },
  ],
} as const;
