import type { Semester } from "./types";

/** Semester 6 — Research literacy, capstone, and professional pathways (~12 h). */
export const SEMESTER_06: Semester = {
  id: "s6",
  number: 6,
  title: "Synthesis: Research Literacy, Capstone, and Professional Pathways",
  description:
    "Reading cryptography and systems papers, evaluating claims, designing a capstone project, communicating risk to stakeholders, and mapping careers without hype.",
  prerequisites: ["Semester 5 complete", "Instructor approval for capstone topic"],
  modules: [
    {
      id: "s6-m1",
      title: "Research Methods for Crypto",
      description: "How to read a preprint, reproduce a benchmark, and spot marketing dressed as science.",
      lessons: [
        {
          id: "s6-m1-l1",
          title: "Paper Reading: Definitions, Assumptions, Theorem vs Implementation Gap",
          synopsis: "Crypto papers vs systems papers; threat model discipline.",
          estimatedMinutes: 85,
          objectives: [
            "Summarize a paper in 5 sentences: problem, model, result, limits, artifact.",
            "Extract explicit and implicit assumptions.",
            "Explain why asymptotics mislead for constants that matter in production.",
          ],
          readings: [
            {
              title: "How to Read an Academic Paper (any CS guide) + one classic crypto abstract",
              studyGuide: "Practice on SNARK intro or BLS aggregation post.",
              estimatedMinutes: 50,
            },
          ],
          lectureOutline: ["Proof systems zoo at brochure depth", "Trusted setup ceremonies", "Benchmark gaming"],
          lab: {
            title: "Annotated Bibliography",
            scenario: "Pick 5 papers or serious reports on one narrow topic (e.g. bridge security).",
            deliverable: "Annotated bib + clustering diagram of ideas.",
            rubricHints: ["Mixes venues", "Notes conflicts between papers"],
          },
          selfCheckQuestions: ["What is the adversary model?", "What did authors not measure?"],
        },
        {
          id: "s6-m1-l2",
          title: "Reproducibility and Open Data Ethics",
          synopsis: "On-chain data analysis pitfalls; labels; survivorship bias.",
          estimatedMinutes: 80,
          objectives: ["List biases in public Dune dashboards.", "Explain event decoding hazards.", "Propose preregistration for an on-chain study."],
          readings: [{ title: "Dune docs + one rigorous chain analytics paper", studyGuide: "Focus on methodology.", estimatedMinutes: 40 }],
          lectureOutline: ["Heuristic labels vs ground truth", "Sybil in datasets", "Privacy of counterparties"],
          lab: {
            title: "Study Preregistration",
            scenario: "Write a one-page prereg for a simple question answerable with public data.",
            deliverable: "Prereg + ethical note + expected failure modes.",
            rubricHints: ["Clear hypothesis", "Defines success metric"],
          },
          selfCheckQuestions: ["When is chain data PII?", "What is p-hacking on-chain?"],
        },
        {
          id: "s6-m1-l3",
          title: "ZK and Modern Crypto Brochure (Honest Depth)",
          synopsis: "What zkSNARKs buy you; recursion; why 'ZK rollup' naming confuses newcomers.",
          estimatedMinutes: 82,
          objectives: ["Separate zero-knowledge from succinctness.", "Explain verifier vs prover cost intuition.", "Name where trusted setup still appears."],
          readings: [{ title: "a16z crypto ZK canon intro + zkSync/starkware educational posts", studyGuide: "Stop at math you can explain aloud.", estimatedMinutes: 45 }],
          lectureOutline: ["STARK vs SNARK tradeoffs hand-wavy", "Data availability with ZK", "Hardware acceleration risks"],
          lab: {
            title: "Explain Like I'm a Skeptical Engineer",
            scenario: "Write 800 words explaining ZK rollups to a senior backend engineer who distrusts hype.",
            deliverable: "Essay + glossary + further reading.",
            rubricHints: ["Names limitations", "Corrects common myths"],
          },
          selfCheckQuestions: ["Does ZK imply privacy?", "What is a soundness bug?"],
        },
      ],
    },
    {
      id: "s6-m2",
      title: "Capstone Preparation",
      description: "Scope, ethics, safety, and communication plan before building or analyzing.",
      lessons: [
        {
          id: "s6-m2-l1",
          title: "Capstone Scoping: Question, Artifact, and Evaluation Plan",
          synopsis: "Avoid science fair vibes; pick falsifiable claims.",
          estimatedMinutes: 78,
          objectives: ["Write capstone one-pager with success metrics.", "Identify stakeholders and harms.", "Plan weekly milestones."],
          readings: [{ title: "Your institution's capstone handbook if any; else MIT project proposal samples", studyGuide: "Steal structure not content.", estimatedMinutes: 25 }],
          lectureOutline: ["Build vs break vs measure tracks", "Advisor matching", "IRB-like self-check for human subjects"],
          lab: {
            title: "Proposal Draft v0",
            scenario: "Submit capstone one-pager for peer review in cohort.",
            deliverable: "One-pager + peer review responses.",
            rubricHints: ["Measurable outcomes", "Risk section"],
          },
          selfCheckQuestions: ["What would make you abandon the project?", "Who could be harmed?"],
        },
        {
          id: "s6-m2-l2",
          title: "Ethics of Disclosure, Whitehat Moves, and Public Communication",
          synopsis: "Responsible timelines; Twitter threads vs coordinated disclosure.",
          estimatedMinutes: 75,
          objectives: ["Draft disclosure email template.", "Explain why partial fixes complicate bounty.", "List comms mistakes in past incidents."],
          readings: [{ title: "CERT disclosure guidelines summary", studyGuide: "Map to on-chain immutability.", estimatedMinutes: 30 }],
          lectureOutline: ["Chain immutability vs upgradeability", "Community panic dynamics", "Legal counsel boundary"],
          lab: {
            title: "Comms Simulation",
            scenario: "Tabletop: critical bug found Friday 6pm before holiday.",
            deliverable: "Timeline + internal/external message drafts (redacted).",
            rubricHints: ["No victim blaming", "Defines freeze vs pause language"],
          },
          selfCheckQuestions: ["When is silent patch ethical?", "Who needs to know first?"],
        },
        {
          id: "s6-m2-l3",
          title: "Presentation Skills for Technical and Executive Audiences",
          synopsis: "Two versions of the same result: depth for engineers, decision framing for leaders.",
          estimatedMinutes: 72,
          objectives: ["Build 10-slide deck with appendix discipline.", "Practice 3-minute elevator version.", "Receive structured peer feedback."],
          readings: [{ title: "Any classic tech talk critique rubric", studyGuide: "Self-score a recorded practice.", estimatedMinutes: 20 }],
          lectureOutline: ["Story arc: stakes → method → result → limits", "Visualizing risk", "Handling hostile Q&A"],
          lab: {
            title: "Dry Run",
            scenario: "Record 12-minute capstone dry run; peers use rubric.",
            deliverable: "Recording link (private) + rubric scores + revision list.",
            rubricHints: ["Timeboxed", "Explicit unknowns slide"],
          },
          selfCheckQuestions: ["What belongs in appendix only?", "How do you end without overselling?"],
        },
      ],
    },
    {
      id: "s6-m3",
      title: "Professional Pathways and Continuing Education",
      description: "Roles, credentials skepticism, and sustainable learning habits.",
      lessons: [
        {
          id: "s6-m3-l1",
          title: "Role Map: Protocol Eng, Security, Data, Product, Policy, Research",
          synopsis: "Skills adjacency graph; how to avoid burning out on noise.",
          estimatedMinutes: 80,
          objectives: ["For three roles, list daily artifacts and failure modes.", "Propose a 6-month learning plan post-course.", "Identify credential inflation vs signal."],
          readings: [{ title: "Public job descriptions from 5 org types", studyGuide: "Extract skill keywords.", estimatedMinutes: 40 }],
          lectureOutline: ["Open source portfolio ethics", "Conference vs deep work tradeoff", "Mentorship norms"],
          lab: {
            title: "Personal Development Plan",
            scenario: "Write PDP with quarterly goals tied to measurable outputs (commits, posts, audits shadowed).",
            deliverable: "PDP + mentor questions list.",
            rubricHints: ["Concrete outputs", "Includes rest/recovery"],
          },
          selfCheckQuestions: ["What is performative learning?", "How do you measure depth?"],
        },
        {
          id: "s6-m3-l2",
          title: "Open Source Contribution Without Exploitation",
          synopsis: "Sustainability of public goods; grant seeking; boundaries.",
          estimatedMinutes: 74,
          objectives: ["Compare grants vs employment tradeoffs.", "Explain maintainer burnout risks.", "Draft contribution agreement checklist."],
          readings: [{ title: "FOSS governance essays (pick 2)", studyGuide: "Note power dynamics.", estimatedMinutes: 35 }],
          lectureOutline: ["CLA vs DCO", "Security expectations on volunteers", "Sponsorship ethics"],
          lab: {
            title: "Contribution Plan",
            scenario: "Pick one OSS repo; propose a bounded contribution with timeline.",
            deliverable: "Issue draft or design doc outline + mentor outreach template.",
            rubricHints: ["Realistic scope", "Shows communication plan"],
          },
          selfCheckQuestions: ["When is unpaid labor harmful?", "What is maintainer capture?"],
        },
        {
          id: "s6-m3-l3",
          title: "Capstone Defense and Portfolio Packaging",
          synopsis: "Final integration: artifact, write-up, retrospective, and honest limitations section.",
          estimatedMinutes: 90,
          objectives: ["Defend capstone in timed Q&A.", "Publish README-quality documentation.", "Write retrospective on what you would redo."],
          readings: [],
          lectureOutline: ["Defense rubric walkthrough", "Archiving reproducible environments", "Long-term maintenance expectations"],
          lab: {
            title: "Capstone Defense",
            scenario: "20-minute presentation + 15-minute Q&A with cohort + instructor.",
            deliverable: "Final report PDF or repo + defense slides + retrospective (500+ words).",
            rubricHints: ["Limitations section required", "Repro steps tested by peer"],
          },
          selfCheckQuestions: ["What did you prove vs narrate?", "What remains dangerously unknown?"],
        },
      ],
    },
  ],
} as const;
