import type { Semester } from "./types";

/** Semester 5 — Security, MEV, privacy, and operations (~12 h). */
export const SEMESTER_05: Semester = {
  id: "s5",
  number: 5,
  title: "Security Engineering, MEV, and Operational Resilience",
  description:
    "Threat modeling for wallets and protocols, smart contract audit literacy, MEV supply chain, privacy technologies, incident response, and running systems that touch crypto safely.",
  prerequisites: ["Semester 4 complete", "Basic scripting comfort helpful but not required"],
  modules: [
    {
      id: "s5-m1",
      title: "Wallet and Key Management Security",
      description: "From seed phrases to hardware signing and organizational HSMs.",
      lessons: [
        {
          id: "s5-m1-l1",
          title: "Key Material Lifecycle: Generation, Storage, Rotation, Destruction",
          synopsis: "Entropy sources, air gaps, multisig rotation ceremonies, and what 'lost keys' means legally and technically.",
          estimatedMinutes: 82,
          objectives: [
            "Enumerate cold vs hot key threats.",
            "Describe a basic 2-of-3 multisig rotation without losing funds.",
            "Explain why screenshots of seeds are catastrophic.",
          ],
          readings: [{ title: "CWE / NIST key management primers (skim)", studyGuide: "Map each control to crypto UX.", estimatedMinutes: 35 }],
          lectureOutline: ["Shamir vs multisig tradeoffs", "Passphrase plausible deniability", "Supply chain of hardware wallets"],
          lab: {
            title: "Household Recovery Plan",
            scenario: "Write a recovery plan for a non-technical family member (testnet practice encouraged).",
            deliverable: "Checklist + threat list + what NOT to do section.",
            rubricHints: ["Mentions social recovery tradeoffs", "No actual seeds"],
          },
          selfCheckQuestions: ["What does multisig not protect against?", "When is cloud backup acceptable?"],
        },
        {
          id: "s5-m1-l2",
          title: "Phishing, Malware, and Transaction Simulation Limits",
          synopsis: "Address poisoning, malicious approvals, clipboard malware, fake support.",
          estimatedMinutes: 80,
          objectives: ["Teach others to read calldata at 'danger colors' level.", "Explain address poisoning.", "List wallet vendor trust assumptions."],
          readings: [{ title: "SlowMist / WalletGuard style writeups (pick 3)", studyGuide: "Extract patterns.", estimatedMinutes: 40 }],
          lectureOutline: ["Permit2 vs classic approvals", "Browser extension threat model", "Human-readable signing limits"],
          lab: {
            title: "Phishing Red Team Tabletop",
            scenario: "Run a 60-minute tabletop: fake airdrop site vs team defenses.",
            deliverable: "After-action report with detection time and policy gaps.",
            rubricHints: ["Blames process not individuals", "Concrete policy deltas"],
          },
          selfCheckQuestions: ["Why can simulation lie?", "What is blind signing?"],
        },
        {
          id: "s5-m1-l3",
          title: "Operational Security for Teams",
          synopsis: "On-call, runbooks, secrets management, CI/CD signing keys for web3 orgs.",
          estimatedMinutes: 85,
          objectives: ["Draft secrets policy for a 10-person startup.", "Explain why Slack is not a vault.", "Outline incident comms template."],
          readings: [{ title: "HashiCorp Vault / 1Password SCIM docs (overview)", studyGuide: "Focus on rotation.", estimatedMinutes: 30 }],
          lectureOutline: ["SOC2-ish mapping optional", "Vendor compromise scenarios", "War room roles"],
          lab: {
            title: "Runbook Skeleton",
            scenario: "Create runbook: suspected hot wallet compromise.",
            deliverable: "Step 0–60 min checklist + external comms hold rules.",
            rubricHints: ["Includes chain pause contacts", "Defines evidence preservation"],
          },
          selfCheckQuestions: ["What is first move if CI secret leaks?", "Who speaks publicly?"],
        },
      ],
    },
    {
      id: "s5-m2",
      title: "Smart Contract Security and Audit Literacy",
      description: "How to read an audit; common vulnerability classes; formal methods brochure.",
      lessons: [
        {
          id: "s5-m2-l1",
          title: "Audit Reports: Severity, Scope, and What They Do Not Say",
          synopsis: "Parsing findings; diff between spec audit vs code audit; time-bounded guarantees.",
          estimatedMinutes: 78,
          objectives: ["Explain scope section pitfalls.", "Rewrite one finding in plain English.", "List residual risks after 'clean' report."],
          readings: [{ title: "OpenZeppelin audit (pick small scoped one)", studyGuide: "Read intro + conclusion.", estimatedMinutes: 45 }],
          lectureOutline: ["Formal verification when worth it", "Bug bar economics", "Continuous review vs point-in-time"],
          lab: {
            title: "Executive Summary",
            scenario: "Summarize a real audit for a non-technical board in 1 page.",
            deliverable: "Summary + 5 questions board should ask engineers.",
            rubricHints: ["Names scope limits", "No 'we are safe'"],
          },
          selfCheckQuestions: ["Why are informational issues still valuable?", "What is diff review coverage?"],
        },
        {
          id: "s5-m2-l2",
          title: "Vulnerability Zoo: Access Control, Logic, Oracle, Decimal, Time",
          synopsis: "Pattern recognition for readers; not a certifying course in exploitation.",
          estimatedMinutes: 90,
          objectives: ["Cluster 20 historical bugs into taxonomy.", "Explain access control vs input validation.", "Discuss responsible disclosure norms."],
          readings: [{ title: "SWC registry (skim categories)", studyGuide: "Flashcards optional.", estimatedMinutes: 40 }],
          lectureOutline: ["Invariant testing mindset", "Symbolic execution brochure", "Economic exploits vs pure bugs"],
          lab: {
            title: "Invariant List",
            scenario: "For a simple lending toy spec, write 10 invariants you'd monitor on-chain.",
            deliverable: "Invariant doc + which are expensive to check.",
            rubricHints: ["Mixes safety and economic", "Notes oracle coupling"],
          },
          selfCheckQuestions: ["What is a business logic bug?", "When is a bug a feature?"],
        },
        {
          id: "s5-m2-l3",
          title: "Bug Bounties and Safe Harbor",
          synopsis: "Coordinated disclosure; whitehat rescue; legal gray zones (non-advice).",
          estimatedMinutes: 75,
          objectives: ["Draft bounty scope boundaries.", "Explain safe harbor statements limits.", "Simulate triage severity call."],
          readings: [{ title: "Immunefi + HackerOne policy examples", studyGuide: "Compare out-of-scope clauses.", estimatedMinutes: 35 }],
          lectureOutline: ["Partial fixes and duplicate rules", "KYC for payouts tradeoffs", "War room legal"],
          lab: {
            title: "Bounty Policy Draft",
            scenario: "Write first-page bounty policy for a new L2 bridge (hypothetical).",
            deliverable: "Policy + triage flowchart.",
            rubricHints: ["Clear out-of-scope", "Defines severity matrix"],
          },
          selfCheckQuestions: ["Why cap rewards?", "What is primacy of rules disputes?"],
        },
      ],
    },
    {
      id: "s5-m3",
      title: "MEV, Privacy, and Credible Neutrality",
      description: "Block production economics, encrypted mempools brochure, zk privacy tradeoffs.",
      lessons: [
        {
          id: "s5-m3-l1",
          title: "MEV Supply Chain: Searchers, Builders, Relays, Validators",
          synopsis: "PBS intuition; why users pay for ordering; local vs global fairness.",
          estimatedMinutes: 88,
          objectives: ["Draw MEV flow diagram post-merge Ethereum.", "Explain sandwich attack at intuition level.", "Discuss censorship pressures on relays."],
          readings: [{ title: "Flashbots docs + PBS explainer", studyGuide: "Focus on trust shifts.", estimatedMinutes: 45 }],
          lectureOutline: ["Private order flow markets", "App-layer mitigations", "SUAVE-style futures (brochure)"],
          lab: {
            title: "MEV Policy Memo",
            scenario: "Your DEX considers OFA partner; write risks/benefits memo for community.",
            deliverable: "2-page memo + decision criteria.",
            rubricHints: ["Acknowledges centralization path", "User welfare lens"],
          },
          selfCheckQuestions: ["Why is private mempool not a silver bullet?", "What is time-bandit attack?"],
        },
        {
          id: "s5-m3-l2",
          title: "Privacy: Tornado Cash Lesson, ZK Brochure, Compliance Reality",
          synopsis: "Privacy as a spectrum; traceability of habits; regulatory response case study (facts only).",
          estimatedMinutes: 80,
          objectives: ["Explain difference between anonymity set and zk proof.", "Discuss wallet fingerprinting.", "List design tensions for compliant privacy."],
          readings: [{ title: "EFF + legal primers on code vs speech (overview)", studyGuide: "Neutral notes.", estimatedMinutes: 40 }],
          lectureOutline: ["Account-based chain privacy limits", "UTXO mix pros/cons", "L2 privacy pools"],
          lab: {
            title: "Privacy Design Sketch",
            scenario: "Design privacy feature for donations without enabling obvious laundering.",
            deliverable: "Threat model + mitigations + why hard.",
            rubricHints: ["No how-to launder", "Honest about limits"],
          },
          selfCheckQuestions: ["What breaks privacy graphs?", "What is compliance by design?"],
        },
        {
          id: "s5-m3-l3",
          title: "Credible Neutrality and Social Layer",
          synopsis: "Why protocols embed politics; client diversity; governance capture resistance.",
          estimatedMinutes: 78,
          objectives: ["Define credible neutrality in one paragraph.", "Give examples of 'neutral' rules that still privilege groups.", "Argue for client diversity with evidence."],
          readings: [{ title: "Vitalik credible neutrality essay", studyGuide: "Apply to one live protocol.", estimatedMinutes: 35 }],
          lectureOutline: ["Rough consensus and running code", "Emergency forks ethics", "Public goods funding"],
          lab: {
            title: "Neutrality Audit",
            scenario: "Pick a protocol parameter; analyze who it advantages over 5 years.",
            deliverable: "Essay 1000 words + counterproposals.",
            rubricHints: ["Specific mechanism", "Avoids ad hominem"],
          },
          selfCheckQuestions: ["Can neutrality be measured?", "What is governance minimalism?"],
        },
      ],
    },
  ],
} as const;
